@echo off
echo 🧹 Cleaning development environment...

echo Stopping all Node processes...
taskkill /f /im node.exe 2>nul

echo Removing .next folder...
if exist .next rmdir /s /q .next

echo Removing node_modules...
if exist node_modules rmdir /s /q node_modules

echo Removing package-lock.json...
if exist package-lock.json del package-lock.json

echo Clearing npm cache...
npm cache clean --force

echo Installing dependencies...
npm install --legacy-peer-deps

echo Starting development server...
npm run dev

echo ✅ Clean development environment ready!
